name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'
      - name: Build Package with swift
        run: swift build
      - name: Build Package with xcodebuild
        run: xcodebuild -scheme ApiVideoPlayer  -destination 'platform=iOS Simulator,name=iPhone 13'
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['workspace']['schemes'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Verify cocoapods
        run: pod lib lint --allow-warnings
      - name: Execute swiftlint
        run: |
          swiftlint
      - name: Build Examples
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild clean build -project Examples/ExampleUIKit/ExampleUIKit.xcodeproj -scheme $scheme -sdk iphoneos
