name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.3'
      - name: Swift version
        uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
        with:
          swift-version: "5.6.0"
      - name: Get swift version
        run: swift --version
      - name: Build Package
        run: swift build -v
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['workspace']['schemes'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild clean build -project Examples/Example/Example.xcodeproj -scheme $scheme -sdk iphoneos
