name: Run unit tests
on: [push]
jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'
      - name: Running tests
        run: xcodebuild -scheme ApiVideoPlayer  -destination 'platform=iOS Simulator,name=iPhone 13' test
